//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.up.onetouch.rest;

import com.up.onetouch.bean.LoginRequest;
import com.up.onetouch.bean.LoginResponse;
import com.up.onetouch.bean.Usuario;
import com.up.onetouch.bean.UsuarioResponse;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class RestClient_
    implements RestClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public RestClient_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
        rootUrl = "";
    }

    @Override
    public void setRootUrl(String rootUrl) {
        this.rootUrl = rootUrl;
    }

    @Override
    public UsuarioResponse persist(Usuario usuario) {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Usuario> requestEntity = new HttpEntity<Usuario>(usuario, httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/user/persist"), HttpMethod.POST, requestEntity, UsuarioResponse.class).getBody();
    }

    @Override
    public LoginResponse login(LoginRequest request) {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<LoginRequest> requestEntity = new HttpEntity<LoginRequest>(request, httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/login/validate"), HttpMethod.POST, requestEntity, LoginResponse.class).getBody();
    }

}
